services:
  - type: web
    name: cloudvault-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://admin:Dpbv0609@cloudvault-cluster.wjoowji.mongodb.net/?retryWrites=true&w=majority&appName=cloudvault-cluster
      - key: JWT_SECRET
        value: Dpbv20010609
