services:
  - type: web
    name: cloudvault-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
      - key: JWT_SECRET